apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmyshow-deployment
  namespace: bhavana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmyshow
  template:
    metadata:
      labels:
        app: bookmyshow
    spec:
      containers:
      - name: bookmyshow
        image: bhavana686/bookmyshow:v4
        ports:
        - containerPort: 3000
